version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-jpillora/dnsmasq:1.1.0}
    entrypoint:
      - "webproc"
      - "--config"
      - "/config/dnsmasq.conf"
      - "--"
      - "dnsmasq"
      - "--no-daemon"
      - "--conf-file=/config/dnsmasq.conf"
      - "--conf-dir=/config"
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
    logging:            #!log
      driver: json-file #!log
      options:          #!log
        max-size: 10m   #!log
    ports:
      - ${DEPLOY_PORT_DNS:-53}:53/udp
      - ${DEPLOY_PORT_DNS:-53}:53/tcp
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    environment:
      - HTTP_USER
      - HTTP_PASS
    healthcheck:
      test: ["CMD", "nslookup", "baidu.com", "127.0.0.1"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - external_network
    volumes:
      - config:/config
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-dnsmasq}.rule=${DEPLOY_ROUTER_WEB:-Host(\`${DEPLOY_SUBDOMAIN:-dnsmasq}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-dnsmasq}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-dnsmasq}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-dnsmasq}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-dnsmasq}.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true

volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-dnsmasq}/config"
