version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-wallabag/wallabag:2.4.1}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-80}:80
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://${DEPLOY_SUBDOMAIN:-wallabag}.${DEPLOY_HOSTNAME}
      - SYMFONY__ENV__LOCALE=zh
      - SYMFONY__ENV__MAILER_HOST=$DEPLOY_MAIL_HOST
      - SYMFONY__ENV__MAILER_USER=$DEPLOY_MAIL_USER
      - SYMFONY__ENV__FROM_EMAIL=${DEPLOY_MAIL_FROM_USER:-wallabag}@$DEPLOY_MAIL_FROM_DOMAIN
      - SYMFONY__ENV__MAILER_PASSWORD=$DEPLOY_MAIL_PASSWORD
    networks:
      - external_network
    volumes:
      - data:/var/www/wallabag/data
      - images:/var/www/wallabag/web/assets/images
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-wallabag}.rule=${DEPLOY_ROUTER_WEB:-Host(\`${DEPLOY_SUBDOMAIN:-wallabag}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-wallabag}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-wallabag}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-wallabag}.loadbalancer.server.port=80"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-wallabag}/data"
  images:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-wallabag}/images"
