version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  registry:
    image: ${DEPLOY_IMAGE_REGISTRY:-registry:2}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_REGISTRY}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_REGISTORY:-5000}:5000
    networks:
      - external_network
    configs:
      - source: registry-config
        target: /etc/docker/registry/config.yml
    volumes:
      - data:/var/lib/registry
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_REGISTRY:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.rule=Host(\`${DEPLOY_SUBDOMAIN:-docker}.${DEPLOY_HOSTNAME}\`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-registry}.loadbalancer.server.port=5000"

#:web|  web:
#:web|    image: ${DEPLOY_IMAGE_WEB:-jessfraz/reg:latest}
#:web|#:log |    logging: *loki-logging
#:web|#:env |    env_file: ${DEPLOY_ENV_WEB}
#:web|#:port-web|    ports:
#:web|#:port-web|      - ${DEPLOY_PORT_WEB:-8080}:8080
#:web|    command: server -r ${DEPLOY_SUBDOMAIN:-docker}.${DEPLOY_HOSTNAME}
#:web|    networks:
#:web|      - external_network
#:web|    deploy:
#:web|      replicas: 1
#:web|      placement:
#:web|        constraints: 
#:web|          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
#:web|      labels:
#:web|        - "traefik.enable=true" #!no-proxy
#:web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}_web.rule=Host(\`${DEPLOY_SUBDOMAIN_WEB:-web-docker}.${DEPLOY_HOSTNAME}\`)"
#:web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}_web.entrypoints=webhttps"
#:web|#:client-ssl-web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}_web.tls.options=sslVerifyClient@file"
#:web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-registry}_web.tls.certresolver=le"
#:web|        - "traefik.http.services.${DEPLOY_STACK_NAME:-registry}_web.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true

configs:
  registry-config:
    file: ${DEPLOY_CONFIG_REGISTRY:-config/config.yml}
    template_driver: golang

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-registry}/data"
  ssl:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-registry}/ssl"
