version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-wikiwi/robots-disallow:0.2.0}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    networks:
      - external_network
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-robotsdisallow}.rule=Path(\`/robots.txt\`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-robotsdisallow}.priority=100"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-robotsdisallow}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-robotsdisallow}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-robotsdisallow}.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true
