version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  aria2:
    # Reference: https://p3terx.com/archives/docker-aria2-pro.html
    image: ${DEPLOY_IMAGE_ARIA2:-p3terx/aria2-pro:latest}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_ARIA2}
    logging:            #!log
      driver: json-file #!log
      options:          #!log
        max-size: 1m    #!log
    ports:
      - ${DEPLOY_PORT_ARIA2_BT:-6888}:${DEPLOY_PORT_ARIA2_BT:-6888}/tcp #!host
      - ${DEPLOY_PORT_ARIA2_BT:-6888}:${DEPLOY_PORT_ARIA2_BT:-6888}/udp #!host
#:host|      - target: ${DEPLOY_PORT_ARIA2_BT:-6888}
#:host|        published: ${DEPLOY_PORT_ARIA2_BT:-6888}
#:host|        protocol: udp
#:host|        mode: host
#:host|      - target: ${DEPLOY_PORT_ARIA2_BT:-6888}
#:host|        published: ${DEPLOY_PORT_ARIA2_BT:-6888}
#:host|        protocol: tcp
#:host|        mode: host
#:port|      - ${DEPLOY_PORT_ARIA2_RPC:-6800}:6800
    environment:
      - LISTEN_PORT=${DEPLOY_PORT_ARIA2_BT:-6888}
      - RPC_PORT=6800
      - RPC_SECRET=${RPC_SECRET:-aria2}
      - PUID
      - PGID
      - UMASK_SET
      - DISK_CACHE
      - IPV6_MODE
      - UPDATE_TRACKERS
      - CUSTOM_TRACKER_URL
      - SPECIAL_MODE
      - TZ
    networks:
      - external_network
    volumes:
      - config:/config
      - download:/downloads
#:media |      - media:$DEPLOY_MEDIA_MOUNT
#:rclone|      - rclone:$DEPLOY_RCLONE_MOUNT
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_ARIA2:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_web.rule=${DEPLOY_ROUTER_ARIA2:-Host(\`${DEPLOY_SUBDOMAIN:-aria2}.${DEPLOY_HOSTNAME}\`)&&PathPrefix(\`/jsonrpc\`,\`/rpc\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_web.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_web.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_web.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-aria2}_web.loadbalancer.server.port=6800"

#:webui|  web:
#:webui|    image: ${DEPLOY_IMAGE_WEB:-p3terx/ariang:latest}
#:webui|    command: --port 80
#:webui|#:log |    logging: *loki-logging
#:webui|#:env |    env_file: ${DEPLOY_ENV_WEB}
#:webui|#:port|    ports:
#:webui|#:port|      - ${DEPLOY_PORT_WEB:-80}:80
#:webui|    networks:
#:webui|      - external_network
#:webui|    deploy:
#:webui|      replicas: 1
#:webui|      placement:
#:webui|        constraints: 
#:webui|          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
#:webui|      labels:
#:webui|        - "traefik.enable=true" #!no-proxy
#:webui|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_aria2.rule=${DEPLOY_ROUTER_WEB:-Host(\`${DEPLOY_SUBDOMAIN:-aria2}.${DEPLOY_HOSTNAME}\`)}"
#:webui|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_aria2.entrypoints=webhttps"
#:webui|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_aria2.tls.options=sslVerifyClient@file"
#:webui|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-aria2}_aria2.tls.certresolver=le"
#:webui|        - "traefik.http.services.${DEPLOY_STACK_NAME:-aria2}_aria2.loadbalancer.server.port=80"

networks:
  external_network:
    external: true

volumes:
  download:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-aria2}/download"
  config:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-aria2}/config"
#:media |  media:
#:media |    driver_opts:
#:media |      type: "nfs"
#:media |      o: "addr=$DEPLOY_MEDIA_HOST,nolock,soft,rw"
#:media |      device: ":$DEPLOY_MEDIA_ROOT"
#:rclone|  rclone:
#:rclone|    driver: "rclone"
#:rclone|    driver_opts:
#:rclone|      remote: "$DEPLOY_RCLONE_REMOTE"
