version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-vectorim/element-web:v1.11.69-rc.0}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-80}:80
    networks:
      - external_network
    configs:
      - source: element-config
        target: /app/config.json
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-element}.rule=Host(\`${DEPLOY_SUBDOMAIN_WEB:-element}.${DEPLOY_HOSTNAME}\`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-element}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-element}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-element}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-element}.loadbalancer.server.port=80"

networks:
  external_network:
    external: true

configs:
  element-config:
    file: ${DEPLOY_CONFIG_ELEMENT:-config/config.json}
    template_driver: golang
