version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-tootsuite/mastodon:v3.2.0}
#:log |    logging: *loki-logging
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-3000}:3000
    env_file: ${DEPLOY_ENV_MASTODON:-config/mastodon.env}
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - system:/mastodon/public/system
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mastodon}.rule=Host(`${DEPLOY_SUBDOMAIN:-mastodon}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mastodon}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mastodon}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-mastodon}.loadbalancer.server.port=3000"

  db:
    image: ${DEPLOY_IMAGE_DB:-postgres:9.6-alpine}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    networks:
      - internal_network
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_DB:-node.labels.ignore != true}

  redis:
    image: ${DEPLOY_IMAGE_REDIS:-redis:6.0-alpine}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_REDIS}
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - redis:/data
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_REDIS:-node.labels.ignore != true}

#  es:
#    image: ${DEPLOY_IMAGE_ES:-docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10}
##:log |    logging: *loki-logging
##:env |    env_file: ${DEPLOY_ENV_ES}
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "cluster.name=es-mastodon"
#      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
#    networks:
#      - internal_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

  streaming:
    image: ${DEPLOY_IMAGE_STREAMING:-tootsuite/mastodon:v3.2.0}
#:log |    logging: *loki-logging
    env_file: ${DEPLOY_ENV_MASTODON:-config/mastodon.env}
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "0.0.0.0:4000:4000"
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_STREAMING:-node.labels.ignore != true}

  sidekiq:
    image: ${DEPLOY_IMAGE_SIDEKIQ:-tootsuite/mastodon:v3.2.0}
#:log |    logging: *loki-logging
    env_file: ${DEPLOY_ENV_MASTODON:-config/mastodon.env}
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - system:/mastodon/public/system
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_SIDEKIQ:-node.labels.ignore != true}
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: ${DEPLOY_IMAGE_TOR:-sirboops/tor:latest}
##:log |    logging: *loki-logging
##:env |    env_file: ${DEPLOY_ENV_TOR}
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: ${DEPLOY_IMAGE_PRIVOXY:-sirboops/privoxy:latest}
##:log |    logging: *loki-logging
##:env |    env_file: ${DEPLOY_ENV_PRIVOXY}
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
    external: true
  internal_network:
    internal: true

volumes:
  system:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mastodon}/public/system"
  redis:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mastodon}/redis"
  postgres:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mastodon}/postgres"
