version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-searx/searx:1.0.0}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    environment:
      BASE_URL: https://${DEPLOY_SUBDOMAIN:-searx}.${DEPLOY_HOSTNAME}/
    networks:
      - external_network
    configs:
      - source: searx-config
        target: /etc/searx/settings.yml
      - source: uwsgi-config
        target: /etc/searx/uwsgi.ini
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-searx}.rule=Host(\`${DEPLOY_SUBDOMAIN:-searx}.${DEPLOY_HOSTNAME}\`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-searx}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-searx}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-searx}.loadbalancer.server.port=8080"

configs:
  searx-config:
    file: ${DEPLOY_CONFIG_SEARX:-config/searx.yml}
  uwsgi-config:
    file: ${DEPLOY_CONFIG_UWSGI:-config/uwsgi.ini}

networks:
  external_network:
    external: true


