version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  grafana:
    image: ${DEPLOY_IMAGE_GRAFANA:-grafana/grafana:10.2.2}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_GRAFANA}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_GRAFANA:-3000}:3000
    networks:
      - external_network
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_GRAFANA:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_grafana.rule=${DEPLOY_ROUTER_GRAFANA:-Host(\`${DEPLOY_SUBDOMAIN_GRAFANA:-grafana}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_grafana.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_grafana.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-plg}_grafana.loadbalancer.server.port=3000"

  loki:
    image: ${DEPLOY_IMAGE_LOKI:-grafana/loki:2.9.2}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_LOKI}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_LOKI:-3100}:3100
    command: "-config.file=/etc/loki/config.yaml"
    networks:
      - internal_network
      - external_network
    volumes:
      - loki:/loki
    configs:
      - source: loki-config
        target: /etc/loki/config.yaml
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_LOKI:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_loki.rule=${DEPLOY_ROUTER_LOKI:-Host(\`${DEPLOY_SUBDOMAIN_LOKI:-loki}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_loki.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_loki.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-plg}_loki.loadbalancer.server.port=3100"

#:promtail|  promtail:
#:promtail|    image: grafana/promtail:2.9.0
#:promtail|    entrypoint: [ "/bin/sh","-c" ]
#:promtail|    command:
#:promtail|      - |
#:promtail|        export HOSTNAME=\$(cat /etc/hostname)
#:promtail|        /usr/bin/promtail -config.file=/etc/promtail/config.yml -config.expand-env=true
#:promtail|    networks:
#:promtail|      - internal_network
#:promtail|    volumes:
#:promtail|      - promtail:/promtail
#:promtail|      - /var/log:/var/log:ro
#:promtail|      - /etc/hostname:/etc/hostname:ro
#:promtail|    configs:
#:promtail|      - source: promtail-config
#:promtail|        target: /etc/promtail/config.yml
#:promtail|    deploy:
#:promtail|      mode: global

#:influxdb|  # Reference: https://github.com/mlabouardy/swarm-tig
#:influxdb|  influxdb:
#:influxdb|    image: ${DEPLOY_IMAGE_INFLUXDB:-influxdb:2}
#:influxdb|#:log |    logging: *loki-logging
#:influxdb|#:env |    env_file: ${DEPLOY_ENV_INFLUXDB}
#:influxdb|    networks:
#:influxdb|      - external_network
#:influxdb|    volumes:
#:influxdb|      - influxdb:/var/lib/influxdb2
#:influxdb|    configs:
#:influxdb|      - source: influxdb-config
#:influxdb|        target: /etc/influxdb2/config.toml
#:influxdb|        uid: '1000'
#:influxdb|        gid: '1000'
#:influxdb|    deploy:
#:influxdb|#:influxdb-mem-limit|      resources:
#:influxdb|#:influxdb-mem-limit|        limits:
#:influxdb|#:influxdb-mem-limit|           memory: '${DEPLOY_INFLUXDB_MEM_LIMIT:-512M}'
#:influxdb|      replicas: 1
#:influxdb|      placement:
#:influxdb|        constraints: 
#:influxdb|          - ${DEPLOY_NODE_INFLUXDB:-node.labels.ignore != true}
#:influxdb|      labels:
#:influxdb|        - "traefik.enable=true" #!no-proxy
#:influxdb|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_influxdb.rule=${DEPLOY_ROUTER_INFLUXDB:-Host(\`${DEPLOY_SUBDOMAIN_INFLUXDB:-influxdb}.${DEPLOY_HOSTNAME}\`)}"
#:influxdb|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_influxdb.entrypoints=webhttps"
#:influxdb|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-plg}_influxdb.tls.certresolver=le"
#:influxdb|        - "traefik.http.services.${DEPLOY_STACK_NAME:-plg}_influxdb.loadbalancer.server.port=8086"

#:telegraf|  telegraf:
#:telegraf|    image: ${DEPLOY_IMAGE_TELEGRF:-telegraf:latest}
#:telegraf|#:log |    logging: *loki-logging
#:telegraf|#:env |    env_file: ${DEPLOY_ENV_TELEGRF}
#:telegraf|    hostname: "{{.Node.Hostname}}"
#:telegraf|    # To bypass the uid remapping when running as root inside /entrypoint.sh
#:telegraf|    entrypoint: "telegraf"
#:telegraf|    user: root
#:telegraf|    command: "--config ${TELEGRAF_CONFIG_URL:-/etc/telegraf/telegraf.conf}"
#:telegraf|    environment:
#:telegraf|      - INFLUX_TOKEN
#:telegraf|    networks:
#:telegraf|      - external_network
#:telegraf|    configs:
#:telegraf|      - source: telegraf-config
#:telegraf|        target: /etc/telegraf/telegraf.conf
#:telegraf|    volumes:
#:telegraf|      - /var/run/docker.sock:/var/run/docker.sock:ro
#:telegraf|    deploy:
#:telegraf|      mode: global

networks:
  internal_network:
    internal: true
  external_network:
    external: true

configs:
  loki-config:
    file: ${DEPLOY_CONFIG_LOKI:-config/loki-config.yaml}
#:promtail|  promtail-config:
#:promtail|    file: ${DEPLOY_CONFIG_PROMTAIL:-config/promtail-config.yaml}
#:telegraf|  telegraf-config:
#:telegraf|    file: ${DEPLOY_CONFIG_TELEGRAF:-config/telegraf.conf}
#:influxdb|  influxdb-config:
#:influxdb|    file: ${DEPLOY_CONFIG_INFLUXDB:-config/influxdb.toml}

volumes:
  grafana:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-plg}/grafana"
  loki:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-plg}/loki"
#:influxdb|  influxdb:
#:influxdb|    driver_opts:
#:influxdb|      type: "nfs"
#:influxdb|      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
#:influxdb|      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-plg}/influxdb"
#:promtail|  promtail:
