version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  mail:
    image: ${DEPLOY_IMAGE_MAILSERVER:-mailserver/docker-mailserver:10.0.0}
#:log |    logging: *loki-logging
#:network-overlay|    ports:
#:network-overlay|#:port-smtp    |      - ${DEPLOY_PORT_MAILSERVER_SMTP:-25}:25
#:network-overlay|#:port-smtps   |      - ${DEPLOY_PORT_MAILSERVER_SMTPS:-465}:465
#:network-overlay|#:port-starttls|      - ${DEPLOY_PORT_MAILSERVER_STARTTLS:-587}:587
#:network-overlay|#:port-pop3    |      - ${DEPLOY_PORT_MAILSERVER_POP3:-110}:110
#:network-overlay|#:port-pop3s   |      - ${DEPLOY_PORT_MAILSERVER_POP3S:-995}:995
#:network-overlay|#:port-imap    |      - ${DEPLOY_PORT_MAILSERVER_IMAP:-143}:143
#:network-overlay|#:port-imaps   |      - ${DEPLOY_PORT_MAILSERVER_IMAPS:-993}:993
#:network-host   |    ports:
#:network-host   |#:port-smtp    |      - target: 25
#:network-host   |#:port-smtp    |        published: ${DEPLOY_PORT_MAILSERVER_SMTP:-25}
#:network-host   |#:port-smtp    |        protocol: tcp
#:network-host   |#:port-smtp    |        mode: host
#:network-host   |#:port-smtps   |      - target: 465
#:network-host   |#:port-smtps   |        published: ${DEPLOY_PORT_MAILSERVER_SMTPS:-465}
#:network-host   |#:port-smtps   |        protocol: tcp
#:network-host   |#:port-smtps   |        mode: host
#:network-host   |#:port-starttls|      - target: 587
#:network-host   |#:port-starttls|        published: ${DEPLOY_PORT_MAILSERVER_STARTTLS:-587}
#:network-host   |#:port-starttls|        protocol: tcp
#:network-host   |#:port-starttls|        mode: host
#:network-host   |#:port-pop3    |      - target: 110
#:network-host   |#:port-pop3    |        published: ${DEPLOY_PORT_MAILSERVER_POP3:-110}
#:network-host   |#:port-pop3    |        protocol: tcp
#:network-host   |#:port-pop3    |        mode: host
#:network-host   |#:port-pop3s   |      - target: 995
#:network-host   |#:port-pop3s   |        published: ${DEPLOY_PORT_MAILSERVER_POP3S:-995}
#:network-host   |#:port-pop3s   |        protocol: tcp
#:network-host   |#:port-pop3s   |        mode: host
#:network-host   |#:port-imap    |      - target: 143
#:network-host   |#:port-imap    |        published: ${DEPLOY_PORT_MAILSERVER_IMAP:-143}
#:network-host   |#:port-imap    |        protocol: tcp
#:network-host   |#:port-imap    |        mode: host
#:network-host   |#:port-imaps   |      - target: 993
#:network-host   |#:port-imaps   |        published: ${DEPLOY_PORT_MAILSERVER_IMAPS:-993}
#:network-host   |#:port-imaps   |        protocol: tcp
#:network-host   |#:port-imaps   |        mode: host
    environment:
      - OVERRIDE_HOSTNAME=${DEPLOY_SUBDOMAIN:-mail}.${DEPLOY_HOSTNAME}
      - ONE_DIR=1
    env_file: ${DEPLOY_ENV_MAILSERVER:-config/mailserver.env}
    networks:
      - external_network
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - config:/tmp/docker-mailserver
#:traefik-ssl|      - traefik:/etc/letsencrypt
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_MAILSERVER:-node.labels.ignore != true}

#:traefik-web|  whoami:
#:traefik-web|    image: docker.io/traefik/whoami:latest
#:traefik-web|    deploy:
#:traefik-web|      replicas: 1
#:traefik-web|      labels:
#:traefik-web|        - "traefik.enable=true"
#:traefik-web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mailserver}.rule=Host(`${DEPLOY_SUBDOMAIN:-mail}.${DEPLOY_HOSTNAME}`)"
#:traefik-web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mailserver}.entrypoints=webhttps"
#:traefik-web|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-mailserver}.tls.certresolver=le"
#:traefik-web|        - "traefik.http.services.${DEPLOY_STACK_NAME:-mailserver}.loadbalancer.server.port=80"

# Reference Project: docker-mailserver
# GitHub:
#   - https://github.com/docker-mailserver/docker-mailserver
# DockerHub:
#   - https://hub.docker.com/r/mailserver/docker-mailserver
# Documentation:
#   - https://docker-mailserver.github.io/docker-mailserver/v10.0

networks:
  external_network:
    external: true

volumes:
  maildata:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mailserver}/maildata"
  mailstate:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mailserver}/mailstate"
  maillogs:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mailserver}/maillogs"
  config:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-mailserver}/config"
#:traefik-ssl|  traefik:
#:traefik-ssl|    driver_opts:
#:traefik-ssl|      type: "nfs"
#:traefik-ssl|      o: "addr=$DEPLOY_TRAEFIK_HOST,nolock,soft,rw"
#:traefik-ssl|      device: ":$DEPLOY_TRAEFIK_ROOT"
