version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-jenkins/jenkins:lts-alpine}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
    ports:
      - 50000:50000
#:port|      - ${DEPLOY_PORT_WEB:-8080}:8080
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - external_network
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jenkins}.rule=${DEPLOY_ROUTER_WEB:-Host(\`${DEPLOY_SUBDOMAIN:-jenkins}.${DEPLOY_HOSTNAME}\`)}"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jenkins}.entrypoints=webhttps"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jenkins}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-jenkins}.loadbalancer.server.port=8080"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jenkins}/data"
