version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-sameersbn/bind:9.16.1-20200524}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
    ports:
      - ${DEPLOY_PORT_DNS:-53}:53/udp
      - ${DEPLOY_PORT_DNS:-53}:53/tcp
#:port|      - ${DEPLOY_PORT_WEB:-10000}:443
    environment:
      - ROOT_PASSWORD
      - WEBMIN_ENABLED
      - WEBMIN_INIT_REDIRECT_PORT=443
      - WEBMIN_INIT_SSL_ENABLED=false
      - WEBMIN_INIT_REFERERS=${DEPLOY_SUBDOMAIN:-bind}.${DEPLOY_HOSTNAME} #!no-proxy
    networks:
      - external_network
    volumes:
      - data:/data
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bind}.rule=Host(\`${DEPLOY_SUBDOMAIN:-bind}.${DEPLOY_HOSTNAME}\`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bind}.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bind}.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bind}.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-bind}.loadbalancer.server.port=10000"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-bind}/data"
