version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  web:
    image: ${DEPLOY_IMAGE_WEB:-codysk/bgmi-all-in-one:1.1.8}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_WEB}
    ports:
#:port|      - ${DEPLOY_PORT_WEB:-80}:80
#:port-transmission-webui|      - ${DEPLOY_PORT_TRANSMISSION_WEBUI:-9091}:9091
      - ${DEPLOY_PORT_TRANSMISSION:-51413}:51413/tcp
      - ${DEPLOY_PORT_TRANSMISSION:-51413}:51413/udp
    environment:
      - BGMI_SOURCE
      - BGMI_ADMIN_TOKEN
      - TZ=Asia/Hongkong
    networks:
      - external_network
    volumes:
      - data:/bgmi
#:rclone|      - rclone:/bgmi/bangumi
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_WEB:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy

        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_web.rule=Host(`${DEPLOY_SUBDOMAIN:-bgmi}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_web.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_web.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_web.tls.certresolver=le"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_web.service=${DEPLOY_STACK_NAME:-bgmi}_web"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-bgmi}_web.loadbalancer.server.port=80"

        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_webui.rule=Host(`webui-${DEPLOY_SUBDOMAIN:-bgmi}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_webui.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_webui.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_webui.tls.certresolver=le"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-bgmi}_webui.service=${DEPLOY_STACK_NAME:-bgmi}_webui"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-bgmi}_webui.loadbalancer.server.port=9091"

networks:
  external_network:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-bgmi}/data"
#:rclone|  rclone:
#:rclone|    driver: "rclone"
#:rclone|    driver_opts:
#:rclone|      remote: "${DEPLOY_RCLONE_REMOTE_BANGUMI:?please set bangumi location}"
