version: "3.8"

x-logging: &loki-logging
    driver: loki
    options:
      loki-url: "${DEPLOY_LOKI_URL}"
      loki-retries: 5
      loki-batch-size: 400

services:
  jellyseerr:
    image: ${DEPLOY_IMAGE_JELLYSEERR:-fallenbagel/jellyseerr:2.1.0}
#:log |    logging: *loki-logging
#:env |    env_file: ${DEPLOY_ENV_JELLYSEERR}
#:port|    ports:
#:port|      - ${DEPLOY_PORT_JELLYSEERR:-5055}:5055
    environment:
      - TZ=Asia/Shanghai
    networks:
      - external_network
    volumes:
      - jellyseerr:/app/config
#:media |      - media:/media
#:rclone|      - rclone:$DEPLOY_RCLONE_LOCAL
    deploy:
      replicas: 1
      placement:
        constraints: 
          - ${DEPLOY_NODE_JELLYSEERR:-node.labels.ignore != true}
      labels:
        - "traefik.enable=true" #!no-proxy
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jellyseerr.rule=Host(`${DEPLOY_SUBDOMAIN_JELLYSEERR:-jellyseerr}.${DEPLOY_HOSTNAME}`)"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jellyseerr.entrypoints=webhttps"
#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jellyseerr.tls.options=sslVerifyClient@file"
        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jellyseerr.tls.certresolver=le"
        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-jellyseerr.loadbalancer.server.port=5055"

#:radarr|  radarr:
#:radarr|    image: ${DEPLOY_IMAGE_RADARR:-linuxserver/radarr:5.15.1}
#:radarr|#:log |    logging: *loki-logging
#:radarr|#:env |    env_file: ${DEPLOY_ENV_RADARR}
#:radarr|#:port|    ports:
#:radarr|#:port|      - ${DEPLOY_PORT_RADARR:-7878}:7878
#:radarr|    environment:
#:radarr|      - PUID=1000
#:radarr|      - PGID=1000
#:radarr|      - TZ=Asia/Shanghai
#:radarr|    networks:
#:radarr|      - external_network
#:radarr|    volumes:
#:radarr|      - radarr:/config
#:radarr|#:media |      - media:/media
#:radarr|#:rclone|      - rclone:$DEPLOY_RCLONE_LOCAL
#:radarr|    deploy:
#:radarr|      replicas: 1
#:radarr|      placement:
#:radarr|        constraints: 
#:radarr|          - ${DEPLOY_NODE_RADARR:-node.labels.ignore != true}
#:radarr|      labels:
#:radarr|        - "traefik.enable=true" #!no-proxy
#:radarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-radarr.rule=Host(`${DEPLOY_SUBDOMAIN_RADARR:-radarr}.${DEPLOY_HOSTNAME}`)"
#:radarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-radarr.entrypoints=webhttps"
#:radarr|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-radarr.tls.options=sslVerifyClient@file"
#:radarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-radarr.tls.certresolver=le"
#:radarr|        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-radarr.loadbalancer.server.port=7878"

#:sonarr|  sonarr:
#:sonarr|    image: ${DEPLOY_IMAGE_SONARR:-linuxserver/sonarr:4.0.10}
#:sonarr|#:log |    logging: *loki-logging
#:sonarr|#:env |    env_file: ${DEPLOY_ENV_SONARR}
#:sonarr|#:port|    ports:
#:sonarr|#:port|      - ${DEPLOY_PORT_SONARR:-8989}:8989
#:sonarr|    environment:
#:sonarr|      - PUID=1000
#:sonarr|      - PGID=1000
#:sonarr|      - TZ=Asia/Shanghai
#:sonarr|    networks:
#:sonarr|      - external_network
#:sonarr|    volumes:
#:sonarr|      - sonarr:/config
#:sonarr|#:media |      - media:/media
#:sonarr|#:rclone|      - rclone:$DEPLOY_RCLONE_LOCAL
#:sonarr|    deploy:
#:sonarr|      replicas: 1
#:sonarr|      placement:
#:sonarr|        constraints: 
#:sonarr|          - ${DEPLOY_NODE_SONARR:-node.labels.ignore != true}
#:sonarr|      labels:
#:sonarr|        - "traefik.enable=true" #!no-proxy
#:sonarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-sonarr.rule=Host(`${DEPLOY_SUBDOMAIN_SONARR:-sonarr}.${DEPLOY_HOSTNAME}`)"
#:sonarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-sonarr.entrypoints=webhttps"
#:sonarr|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-sonarr.tls.options=sslVerifyClient@file"
#:sonarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-sonarr.tls.certresolver=le"
#:sonarr|        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-sonarr.loadbalancer.server.port=8989"

#:jackett|  jackett:
#:jackett|    image: ${DEPLOY_IMAGE_JACKETT:-linuxserver/jackett:0.22.1079}
#:jackett|#:log |    logging: *loki-logging
#:jackett|#:env |    env_file: ${DEPLOY_ENV_JACKETT}
#:jackett|#:port|    ports:
#:jackett|#:port|      - ${DEPLOY_PORT_JACKETT:-9117}:9117
#:jackett|    environment:
#:jackett|      - PUID=1000
#:jackett|      - PGID=1000
#:jackett|      - TZ=Asia/Shanghai
#:jackett|      - AUTO_UPDATE=true
#:jackett|    networks:
#:jackett|      - external_network
#:jackett|    volumes:
#:jackett|      - jackett:/config
#:jackett|#:media |      - media:/media
#:jackett|#:rclone|      - rclone:$DEPLOY_RCLONE_LOCAL
#:jackett|    deploy:
#:jackett|      replicas: 1
#:jackett|      placement:
#:jackett|        constraints: 
#:jackett|          - ${DEPLOY_NODE_JACKETT:-node.labels.ignore != true}
#:jackett|      labels:
#:jackett|        - "traefik.enable=true" #!no-proxy
#:jackett|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jackett.rule=Host(`${DEPLOY_SUBDOMAIN_JACKETT:-jackett}.${DEPLOY_HOSTNAME}`)"
#:jackett|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jackett.entrypoints=webhttps"
#:jackett|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jackett.tls.options=sslVerifyClient@file"
#:jackett|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jackett.tls.certresolver=le"
#:jackett|        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-jackett.loadbalancer.server.port=9117"

#:flaresolverr|  flaresolverr:
#:flaresolverr|    image: ${DEPLOY_IMAGE_FLARESOLVERR:-flaresolverr/flaresolverr:v3.3.21}
#:flaresolverr|#:log |    logging: *loki-logging
#:flaresolverr|#:env |    env_file: ${DEPLOY_ENV_FLARESOLVERR}
#:flaresolverr|#:port|    ports:
#:flaresolverr|#:port|      - ${DEPLOY_PORT_FLARESOLVERR:-8191}:8191
#:flaresolverr|    environment:
#:flaresolverr|      - TZ=Asia/Shanghai
#:flaresolverr|      - LOG_LEVEL=${LOG_LEVEL:-info}
#:flaresolverr|      - LOG_HTML=${LOG_HTML:-false}
#:flaresolverr|      - CAPTCHA_SOLVER=${DEPLOY_APP_FLARESOLVERR_CAPTCHA_SOLVER:-none}
#:flaresolverr|    networks:
#:flaresolverr|      - external_network
#:flaresolverr|    deploy:
#:flaresolverr|      replicas: 1
#:flaresolverr|      placement:
#:flaresolverr|        constraints: 
#:flaresolverr|          - ${DEPLOY_NODE_FLARESOLVERR:-node.labels.ignore != true}
#:flaresolverr|      labels:
#:flaresolverr|        - "traefik.enable=true" #!no-proxy
#:flaresolverr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-flaresolverr.rule=Host(`${DEPLOY_SUBDOMAIN_FLARESOLVERR:-flaresolverr}.${DEPLOY_HOSTNAME}`)"
#:flaresolverr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-flaresolverr.entrypoints=webhttps"
#:flaresolverr|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-flaresolverr.tls.options=sslVerifyClient@file"
#:flaresolverr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-flaresolverr.tls.certresolver=le"
#:flaresolverr|        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-flaresolverr.loadbalancer.server.port=8191"

#:jproxy|  jproxy:
#:jproxy|    image: ${DEPLOY_IMAGE_JPROXY:-luckypuppy514/jproxy:v3.4.4}
#:jproxy|#:log |    logging: *loki-logging
#:jproxy|#:env |    env_file: ${DEPLOY_ENV_JPROXY}
#:jproxy|#:port|    ports:
#:jproxy|#:port|      - ${DEPLOY_PORT_JPROXY:-8117}:8117
#:jproxy|    environment:
#:jproxy|      - TZ=Asia/Shanghai
#:jproxy|      - LOG_LEVEL=${LOG_LEVEL:-info}
#:jproxy|      - LOG_HTML=${LOG_HTML:-false}
#:jproxy|      - JAVA_OPTS=${DEPLOY_APP_JPROXY_JAVA_OPTS:--Xmx512m}
#:jproxy|    networks:
#:jproxy|      - external_network
#:jproxy|    volumes:
#:jproxy|      - jproxy:/app/database
#:jproxy|    deploy:
#:jproxy|      replicas: 1
#:jproxy|      placement:
#:jproxy|        constraints: 
#:jproxy|          - ${DEPLOY_NODE_JPROXY:-node.labels.ignore != true}
#:jproxy|      labels:
#:jproxy|        - "traefik.enable=true" #!no-proxy
#:jproxy|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jproxy.rule=Host(`${DEPLOY_SUBDOMAIN_JPROXY:-jproxy}.${DEPLOY_HOSTNAME}`)"
#:jproxy|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jproxy.entrypoints=webhttps"
#:jproxy|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jproxy.tls.options=sslVerifyClient@file"
#:jproxy|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-jproxy.tls.certresolver=le"
#:jproxy|        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-jproxy.loadbalancer.server.port=8117"

#:prowlarr|  prowlarr:
#:prowlarr|    image: ${DEPLOY_IMAGE_PROWLARR:-linuxserver/prowlarr:1.27.0}
#:prowlarr|#:log |    logging: *loki-logging
#:prowlarr|#:env |    env_file: ${DEPLOY_ENV_PROWLARR}
#:prowlarr|#:port|    ports:
#:prowlarr|#:port|      - ${DEPLOY_PORT_PROWLARR:-9696}:9696
#:prowlarr|    environment:
#:prowlarr|      - PUID=1000
#:prowlarr|      - PGID=1000
#:prowlarr|      - TZ=Asia/Shanghai
#:prowlarr|    networks:
#:prowlarr|      - external_network
#:prowlarr|    volumes:
#:prowlarr|      - prowlarr:/config
#:prowlarr|    deploy:
#:prowlarr|      replicas: 1
#:prowlarr|      placement:
#:prowlarr|        constraints: 
#:prowlarr|          - ${DEPLOY_NODE_PROWLARR:-node.labels.ignore != true}
#:prowlarr|      labels:
#:prowlarr|        - "traefik.enable=true" #!no-proxy
#:prowlarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-prowlarr.rule=Host(`${DEPLOY_SUBDOMAIN_PROWLARR:-prowlarr}.${DEPLOY_HOSTNAME}`)"
#:prowlarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-prowlarr.entrypoints=webhttps"
#:prowlarr|#:client-ssl|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-prowlarr.tls.options=sslVerifyClient@file"
#:prowlarr|        - "traefik.http.routers.${DEPLOY_STACK_NAME:-jellyseerr}-prowlarr.tls.certresolver=le"
#:prowlarr|        - "traefik.http.services.${DEPLOY_STACK_NAME:-jellyseerr}-prowlarr.loadbalancer.server.port=9696"

networks:
  external_network:
    external: true

volumes:
  jellyseerr:
    driver_opts:
      type: "nfs"
      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jellyseerr}/jellyseerr"
#:radarr|  radarr:
#:radarr|    driver_opts:
#:radarr|      type: "nfs"
#:radarr|      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
#:radarr|      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jellyseerr}/radarr"
#:sonarr|  sonarr:
#:sonarr|    driver_opts:
#:sonarr|      type: "nfs"
#:sonarr|      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
#:sonarr|      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jellyseerr}/sonarr"
#:jackett|  jackett:
#:jackett|    driver_opts:
#:jackett|      type: "nfs"
#:jackett|      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
#:jackett|      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jellyseerr}/jackett"
#:jproxy|  jproxy:
#:jproxy|    driver_opts:
#:jproxy|      type: "nfs"
#:jproxy|      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
#:jproxy|      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jellyseerr}/jproxy"
#:prowlarr|  prowlarr:
#:prowlarr|    driver_opts:
#:prowlarr|      type: "nfs"
#:prowlarr|      o: "addr=$DEPLOY_DATA_HOST,nolock,soft,rw"
#:prowlarr|      device: ":$DEPLOY_DATA_ROOT/${DEPLOY_STACK_NAME:-jellyseerr}/prowlarr"
#:media |  media:
#:media |    driver_opts:
#:media |      type: "nfs"
#:media |      o: "addr=$DEPLOY_MEDIA_HOST,nolock,soft,rw"
#:media |      device: ":$DEPLOY_MEDIA_ROOT"
#:rclone|  rclone:
#:rclone|    driver: "rclone"
#:rclone|    driver_opts:
#:rclone|      remote: "$DEPLOY_RCLONE_REMOTE"
